secret:
  create: false
  existingName: safespot-secret
apiCore:
  image:
    repository: ghcr.io/project-safespot/safespot-api-core
    tag: fb6bfa7
    pullPolicy: Always
apiPublicRead:
  image:
    repository: ghcr.io/project-safespot/safespot-api-public-read
    tag: fb6bfa7
    pullPolicy: Always
externalIngestion:
  image:
    repository: ghcr.io/project-safespot/safespot-external-ingestion
    tag: fb6bfa7
    pullPolicy: Always
nginx:
  image:
    repository: ghcr.io/project-safespot/safespot-nginx
    tag: b4b1107
    pullPolicy: Always
