apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-core
  namespace: {{ .Values.namespace }}
  labels:
    app: api-core
    env: {{ .Values.env | default "dev" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ index .Values.serviceAccount.apiCore.annotations "eks.amazonaws.com/role-arn" }}
