apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-public-read
  namespace: {{ .Values.namespace }}
  labels:
    app: api-public-read
    env: {{ .Values.env | default "dev" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ index .Values.serviceAccount.apiPublicRead.annotations "eks.amazonaws.com/role-arn" }}
