apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-ingestion
  namespace: {{ .Values.namespace }}
  labels:
    app: external-ingestion
    env: {{ .Values.env | default "dev" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ index .Values.serviceAccount.externalIngestion.annotations "eks.amazonaws.com/role-arn" }}
