apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-core-netpol
  namespace: {{ .Values.namespace }}
  labels:
    app: api-core
    env: {{ .Values.env | default "dev" }}
spec:
  podSelector:
    matchLabels:
      app: api-core
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ingress
      ports:
        - port: 8080
  egress:
    - {}
