apiVersion: v1
kind: Service
metadata:
  name: api-core
  namespace: {{ .Values.namespace }}
  labels:
    app: api-core
    env: {{ .Values.env | default "dev" }}
spec:
  selector:
    app: api-core
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
