apiVersion: v1
kind: Service
metadata:
  name: external-ingestion
  namespace: {{ .Values.namespace }}
  labels:
    app: external-ingestion
    env: {{ .Values.env | default "dev" }}
spec:
  selector:
    app: external-ingestion
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
