apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safespot-api-ingress
  namespace: application
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: safespot.local
      http:
        paths:
          - path: /api/core(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-core
                port:
                  number: 8080
          - path: /api/public(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-public-read
                port:
                  number: 8080