apiVersion: v1
kind: ConfigMap
metadata:
  name: safespot-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: safespot
    service: safespot
    env: {{ .Values.global.env }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.configmap.springProfilesActive | quote }}

  DB_HOST: {{ .Values.configmap.dbHost | quote }}
  DB_PORT: {{ .Values.configmap.dbPort | quote }}
  DB_NAME: {{ .Values.configmap.dbName | quote }}

  REDIS_HOST: {{ .Values.configmap.redisHost | quote }}
  REDIS_PORT: {{ .Values.configmap.redisPort | quote }}

  AWS_REGION: {{ .Values.configmap.awsRegion | quote }}
  AWS_ENDPOINT: {{ .Values.configmap.awsEndpoint | quote }}
  AWS_ENDPOINT_URL: {{ .Values.configmap.awsEndpoint | quote }}
  SQS_ENDPOINT: {{ .Values.configmap.awsEndpoint | quote }}

  SPRING_DATASOURCE_URL: {{ .Values.configmap.springDatasourceUrl | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.configmap.springDataRedisHost | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.configmap.springDataRedisPort | quote }}

  SAFESPOT_SQS_QUEUE_URL: {{ .Values.configmap.safespotSqsQueueUrl | quote }}
  SQS_CORE_EVENT_QUEUE_URL: {{ .Values.configmap.safespotSqsQueueUrl | quote }}
