apiVersion: v1
kind: ConfigMap
metadata:
  name: db-migration-sql
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-2"
data:
  V1__init.sql: |
{{ .Files.Get "migrations/V1__init.sql" | indent 4 }}
  V2__insert_external_api_source.sql: |
{{ .Files.Get "migrations/V2__insert_external_api_source.sql" | indent 4 }}
  V3__fix_seoul_shelter_earthquake_source_url.sql: |
{{ .Files.Get "migrations/V3__fix_seoul_shelter_earthquake_source_url.sql" | indent 4 }}
  V4__insert_shelter_seed_data_FLOOD_type.sql: |
{{ .Files.Get "migrations/V4__insert_shelter_seed_data_FLOOD_type.sql" | indent 4 }}
  V5__align_disaster_alert_read_model_contract.sql: |
{{ .Files.Get "migrations/V5__align_disaster_alert_read_model_contract.sql" | indent 4 }}
  V6__create_test_scenario_record.sql: |
{{ .Files.Get "migrations/V6__create_test_scenario_record.sql" | indent 4 }}
  V7__fix_test_scenario_record_schema.sql: |
{{ .Files.Get "migrations/V7__fix_test_scenario_record_schema.sql" | indent 4 }}
  V8__fix_external_api_source_contracts.sql: |
{{ .Files.Get "migrations/V8__fix_external_api_source_contracts.sql" | indent 4 }}
