{{- if .Values.apiPublicRead.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: safespot-api-public-read-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apiPublicRead.name }}
    service: {{ .Values.apiPublicRead.name }}
    env: {{ .Values.global.env }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.configmap.springProfilesActive | quote }}
  DB_HOST: {{ .Values.configmap.database.readerHost | quote }}
  DB_PORT: {{ .Values.configmap.database.port | quote }}
  DB_NAME: {{ .Values.configmap.database.name | quote }}
  REDIS_HOST: {{ .Values.configmap.redis.host | quote }}
  REDIS_PORT: {{ .Values.configmap.redis.port | quote }}
  AWS_REGION: {{ .Values.configmap.aws.region | quote }}
  {{- if .Values.configmap.aws.endpoint }}
  AWS_ENDPOINT: {{ .Values.configmap.aws.endpoint | quote }}
  AWS_ENDPOINT_URL: {{ .Values.configmap.aws.endpoint | quote }}
  SQS_ENDPOINT: {{ .Values.configmap.aws.endpoint | quote }}
  SAFESPOT_AWS_SQS_ENDPOINT: {{ .Values.configmap.aws.endpoint | quote }}
  {{- end }}
  SPRING_FLYWAY_ENABLED: "false"
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.configmap.database.readerHost .Values.configmap.database.port .Values.configmap.database.name | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.configmap.redis.host | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.configmap.redis.port | quote }}
  SAFESPOT_CACHE_REGENERATION_PUBLISHER_MODE: "sqs"
  SAFESPOT_CACHE_REGENERATION_QUEUE_URL: {{ .Values.configmap.sqs.cacheRegenerationQueueUrl | quote }}
  {{- if .Values.configmap.apiPublicRead.contextPath }}
  SERVER_SERVLET_CONTEXT_PATH: {{ .Values.configmap.apiPublicRead.contextPath | quote }}
  {{- end }}
{{- end }}
