{{- if .Values.apiPublicRead.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiPublicRead.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apiPublicRead.name }}
    service: {{ .Values.apiPublicRead.name }}
    env: {{ .Values.global.env }}
spec:
  replicas: {{ .Values.apiPublicRead.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apiPublicRead.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiPublicRead.name }}
        service: {{ .Values.apiPublicRead.name }}
        env: {{ .Values.global.env }}
    spec:
      serviceAccountName: {{ .Values.apiPublicRead.name }}
      containers:
        - name: {{ .Values.apiPublicRead.name }}
          image: "{{ .Values.apiPublicRead.image.repository }}:{{ .Values.apiPublicRead.image.tag }}"
          imagePullPolicy: {{ .Values.apiPublicRead.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.apiPublicRead.port }}
          envFrom:
            - configMapRef:
                name: safespot-api-public-read-config
            - secretRef:
                name: {{ .Values.secret.existingName }}
          resources:
            {{- toYaml .Values.apiPublicRead.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: {{ .Values.apiPublicRead.probes.startupPath }}
              port: {{ .Values.apiPublicRead.port }}
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.apiPublicRead.probes.readinessPath }}
              port: {{ .Values.apiPublicRead.port }}
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.apiPublicRead.probes.livenessPath }}
              port: {{ .Values.apiPublicRead.port }}
            periodSeconds: 10
{{- end }}
