{{- if .Values.secret.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.existingName }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app: safespot
    service: safespot
    env: {{ .Values.global.env }}
spec:
  refreshInterval: {{ .Values.secret.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secret.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secret.existingName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.secret.externalSecret.remoteRefs.dbUser }}
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secret.externalSecret.remoteRefs.dbPassword }}
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: {{ .Values.secret.externalSecret.remoteRefs.dbUser }}
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ .Values.secret.externalSecret.remoteRefs.dbPassword }}
    - secretKey: JWT_ACCESS_TOKEN_KEY
      remoteRef:
        key: {{ .Values.secret.externalSecret.remoteRefs.jwtAccessTokenKey }}
    - secretKey: JWT_REFRESH_TOKEN_KEY
      remoteRef:
        key: {{ .Values.secret.externalSecret.remoteRefs.jwtRefreshTokenKey }}
    - secretKey: OPENAPI_SERVICE_KEY
      remoteRef:
        key: {{ .Values.secret.externalSecret.remoteRefs.openapiServiceKey }}
    - secretKey: WEATHER_API_KEY
      remoteRef:
        key: {{ .Values.secret.externalSecret.remoteRefs.weatherApiKey }}
    - secretKey: AIR_QUALITY_API_KEY
      remoteRef:
        key: {{ .Values.secret.externalSecret.remoteRefs.airQualityApiKey }}
{{- end }}
