{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safespot-api-core-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.apiCore.healthcheckPath }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}
    {{- $lbAttrs := include "safespot.albLoadBalancerAttributes" . | trim }}
    {{- if $lbAttrs }}
    alb.ingress.kubernetes.io/load-balancer-attributes: {{ $lbAttrs | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.apiCore.path }}
            pathType: {{ .Values.ingress.apiCore.pathType }}
            backend:
              service:
                name: {{ .Values.apiCore.name }}
                port:
                  number: 80
{{- end }}
