apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway:10
          args:
            - migrate
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://{{ .Values.configmap.database.writerHost }}:{{ .Values.configmap.database.port }}/{{ .Values.configmap.database.name }}
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingName }}
                  key: DB_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingName }}
                  key: DB_PASSWORD
          volumeMounts:
            - name: sql
              mountPath: /flyway/sql
      restartPolicy: Never
      {{- with .Values.scheduling.dbMigration.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.dbMigration.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.dbMigration.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: sql
          configMap:
            name: db-migration-sql
