{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.existingName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: safespot
    service: safespot
    env: {{ .Values.global.env }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.dbUser | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  JWT_ACCESS_TOKEN_KEY: {{ .Values.secret.jwtAccessTokenKey | quote }}
  JWT_REFRESH_TOKEN_KEY: {{ .Values.secret.jwtRefreshTokenKey | quote }}
  OPENAPI_SERVICE_KEY: {{ .Values.secret.openapiServiceKey | quote }}
  WEATHER_API_KEY: {{ .Values.secret.weatherApiKey | quote }}
  AIR_QUALITY_API_KEY: {{ .Values.secret.airQualityApiKey | quote }}
{{- end }}
