{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.existingName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: safespot
    service: safespot
    env: {{ .Values.global.env }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsSecretAccessKey | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  SAFESPOT_JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  SAFESPOT_JWT_EXPIRATION: {{ .Values.secret.jwtExpiration | quote }}
{{- end }}
