{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.existingName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: safespot
    service: safespot
    env: {{ .Values.global.env }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.dbUser | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  SAFESPOT_JWT_SECRET: {{ .Values.secret.jwtAccessTokenKey | quote }}
  JWT_REFRESH_TOKEN_KEY: {{ .Values.secret.jwtRefreshTokenKey | quote }}
  SEOUL_API_KEY: {{ .Values.secret.seoulApiKey | quote }}
  MOIS_API_KEY: {{ .Values.secret.moisApiKey | quote }}
  SAFETY_DATA_ALERT_API_KEY: {{ .Values.secret.moisApiKey | quote }}
  DATA_GO_KR_API_KEY: {{ .Values.secret.dataGoKrApiKey | quote }}
  KMA_API_KEY: {{ .Values.secret.dataGoKrApiKey | quote }}
  AIR_KOREA_API_KEY: {{ .Values.secret.dataGoKrApiKey | quote }}
  FORESTRY_API_KEY: {{ .Values.secret.dataGoKrApiKey | quote }}
{{- end }}
