{{- if and .Values.apiPublicRead.enabled .Values.apiPublicReadSurge.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiPublicReadSurge.service.name }}
  namespace: {{ .Values.global.namespace }}
  {{- with .Values.apiPublicReadSurge.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.apiPublicReadSurge.name }}
    service: {{ .Values.apiPublicRead.name }}
    component: surge
    env: {{ .Values.global.env }}
spec:
  selector:
    app: {{ .Values.apiPublicReadSurge.name }}
    service: {{ .Values.apiPublicRead.name }}
    component: surge
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.apiPublicReadSurge.port }}
      protocol: TCP
  type: ClusterIP
{{- end }}
