{{- if .Values.apiCore.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiCore.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apiCore.name }}
    env: {{ .Values.global.env }}
  {{- if .Values.apiCore.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.apiCore.serviceAccount.roleArn }}
  {{- end }}
{{- end }}
---
{{- if .Values.apiPublicRead.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiPublicRead.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apiPublicRead.name }}
    env: {{ .Values.global.env }}
  {{- if .Values.apiPublicRead.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.apiPublicRead.serviceAccount.roleArn }}
  {{- end }}
{{- end }}
---
{{- if .Values.externalIngestion.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalIngestion.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.externalIngestion.name }}
    env: {{ .Values.global.env }}
  {{- if .Values.externalIngestion.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.externalIngestion.serviceAccount.roleArn }}
  {{- end }}
{{- end }}
---
{{- if .Values.scenarioSimulator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scenarioSimulator.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.scenarioSimulator.name }}
    env: {{ .Values.global.env }}
  {{- if .Values.scenarioSimulator.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.scenarioSimulator.serviceAccount.roleArn }}
  {{- end }}
{{- end }}
