{{- if .Values.apiPublicRead.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiPublicRead.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.apiPublicRead.name }}
    service: {{ .Values.apiPublicRead.name }}
    env: {{ .Values.global.env }}
spec:
  selector:
    app: {{ .Values.apiPublicRead.name }}
    service: {{ .Values.apiPublicRead.name }}
  ports:
    - name: http
      port: {{ .Values.apiPublicRead.port }}
      targetPort: {{ .Values.apiPublicRead.port }}
      protocol: TCP
  type: ClusterIP
{{- end }}
