apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safespot-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/project-safespot/safespot-application-k8s-manifest.git
    targetRevision: main
    path: charts/safespot
    helm:
      valueFiles:
        - values.yaml
        - values-aws-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
