apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safespot-app-local
  namespace: argocd
  labels:
    env: local
spec:
  project: default
  source:
    repoURL: https://github.com/project-safespot/safespot-application-k8s-manifest.git
    targetRevision: deploy/local
    path: charts/safespot-app
    helm:
      valueFiles:
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
