apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: safespot-secret
  namespace: {{ .Values.namespace }}
  labels:
    env: {{ .Values.env | default "dev" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: safespot-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.secretName }}
